import type { ExerciseEquipmentType } from './schema';

// CLAUDE.md "Seed exercise list": ship a set of common movements so a new user isn't
// creating everything by hand. Generic names ("Chest press," never "Hammer Strength
// chest press") — equipment brand is a separate attribute resolved per gym (step 4).
// restSeconds/weightIncrement/repFloor are intentionally omitted here: every seeded
// exercise starts on the global settings default (null) until a user overrides it.
//
// GENERATED from notch-seed-exercises.csv — do not hand-edit. Add rows to the CSV and
// regenerate, or the two drift out of sync. Grouped by equipment type, then by the
// canonical muscle-group order in constants/muscleGroups.ts.
//
// Names here are also the identity used by db/bootstrap.ts's ensureSeedExercises,
// which inserts any seed row whose name isn't already in the library — so adding to
// this list reaches existing installs too. Renaming an entry therefore reads as a new
// exercise and leaves the old one behind; add and remove deliberately, don't rename.
export interface SeedExercise {
  name: string;
  muscleGroup: string;
  equipmentType: ExerciseEquipmentType;
}

export const SEED_EXERCISES: SeedExercise[] = [
  // Barbell
  { name: 'Bench press', muscleGroup: 'Chest', equipmentType: 'barbell' },
  { name: 'Incline bench press', muscleGroup: 'Chest', equipmentType: 'barbell' },
  { name: 'Decline bench press', muscleGroup: 'Chest', equipmentType: 'barbell' },
  { name: 'Floor press', muscleGroup: 'Chest', equipmentType: 'barbell' },
  { name: 'Reverse-grip bench press', muscleGroup: 'Chest', equipmentType: 'barbell' },
  { name: 'Deadlift', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'Deficit deadlift', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'Rack pull', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'Barbell row', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'Pendlay row', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'T-bar row', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'Landmine row', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'Power clean', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'Hang clean', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'Barbell pullover', muscleGroup: 'Back', equipmentType: 'barbell' },
  { name: 'Overhead press', muscleGroup: 'Shoulders', equipmentType: 'barbell' },
  { name: 'Seated overhead press', muscleGroup: 'Shoulders', equipmentType: 'barbell' },
  { name: 'Push press', muscleGroup: 'Shoulders', equipmentType: 'barbell' },
  { name: 'Landmine press', muscleGroup: 'Shoulders', equipmentType: 'barbell' },
  { name: 'Upright row', muscleGroup: 'Shoulders', equipmentType: 'barbell' },
  { name: 'Barbell curl', muscleGroup: 'Biceps', equipmentType: 'barbell' },
  { name: 'EZ-bar curl', muscleGroup: 'Biceps', equipmentType: 'barbell' },
  { name: 'Preacher curl', muscleGroup: 'Biceps', equipmentType: 'barbell' },
  { name: 'Reverse curl', muscleGroup: 'Biceps', equipmentType: 'barbell' },
  { name: 'Barbell drag curl', muscleGroup: 'Biceps', equipmentType: 'barbell' },
  { name: 'Close-grip bench press', muscleGroup: 'Triceps', equipmentType: 'barbell' },
  { name: 'Skull crusher', muscleGroup: 'Triceps', equipmentType: 'barbell' },
  { name: 'Barbell shrug', muscleGroup: 'Traps', equipmentType: 'barbell' },
  { name: 'Back squat', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Front squat', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Box squat', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Pause squat', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Safety bar squat', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Barbell split squat', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Barbell lunge', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Barbell reverse lunge', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Barbell step-up', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Trap bar deadlift', muscleGroup: 'Quads', equipmentType: 'barbell' },
  { name: 'Romanian deadlift', muscleGroup: 'Hamstrings', equipmentType: 'barbell' },
  { name: 'Stiff-leg deadlift', muscleGroup: 'Hamstrings', equipmentType: 'barbell' },
  { name: 'Good morning', muscleGroup: 'Hamstrings', equipmentType: 'barbell' },
  { name: 'Sumo deadlift', muscleGroup: 'Glutes', equipmentType: 'barbell' },
  { name: 'Hip thrust', muscleGroup: 'Glutes', equipmentType: 'barbell' },
  { name: 'Barbell calf raise', muscleGroup: 'Calves', equipmentType: 'barbell' },
  { name: 'Barbell wrist curl', muscleGroup: 'Forearms', equipmentType: 'barbell' },
  { name: 'Barbell reverse wrist curl', muscleGroup: 'Forearms', equipmentType: 'barbell' },
  { name: 'Behind-the-back barbell wrist curl', muscleGroup: 'Forearms', equipmentType: 'barbell' },

  // Dumbbell
  { name: 'Dumbbell bench press', muscleGroup: 'Chest', equipmentType: 'dumbbell' },
  { name: 'Incline dumbbell press', muscleGroup: 'Chest', equipmentType: 'dumbbell' },
  { name: 'Decline dumbbell press', muscleGroup: 'Chest', equipmentType: 'dumbbell' },
  { name: 'Dumbbell floor press', muscleGroup: 'Chest', equipmentType: 'dumbbell' },
  { name: 'Neutral-grip dumbbell press', muscleGroup: 'Chest', equipmentType: 'dumbbell' },
  { name: 'Dumbbell squeeze press', muscleGroup: 'Chest', equipmentType: 'dumbbell' },
  { name: 'Dumbbell fly', muscleGroup: 'Chest', equipmentType: 'dumbbell' },
  { name: 'Incline dumbbell fly', muscleGroup: 'Chest', equipmentType: 'dumbbell' },
  { name: 'Dumbbell row', muscleGroup: 'Back', equipmentType: 'dumbbell' },
  { name: 'Single-arm dumbbell row', muscleGroup: 'Back', equipmentType: 'dumbbell' },
  { name: 'Chest-supported dumbbell row', muscleGroup: 'Back', equipmentType: 'dumbbell' },
  { name: 'Renegade row', muscleGroup: 'Back', equipmentType: 'dumbbell' },
  { name: 'Dumbbell pullover', muscleGroup: 'Back', equipmentType: 'dumbbell' },
  { name: 'Incline dumbbell row', muscleGroup: 'Back', equipmentType: 'dumbbell' },
  { name: 'Dumbbell rear delt row', muscleGroup: 'Back', equipmentType: 'dumbbell' },
  { name: 'Dumbbell shoulder press', muscleGroup: 'Shoulders', equipmentType: 'dumbbell' },
  { name: 'Seated dumbbell press', muscleGroup: 'Shoulders', equipmentType: 'dumbbell' },
  { name: 'Arnold press', muscleGroup: 'Shoulders', equipmentType: 'dumbbell' },
  { name: 'Lateral raise', muscleGroup: 'Shoulders', equipmentType: 'dumbbell' },
  { name: 'Leaning lateral raise', muscleGroup: 'Shoulders', equipmentType: 'dumbbell' },
  { name: 'Front raise', muscleGroup: 'Shoulders', equipmentType: 'dumbbell' },
  { name: 'Rear delt fly', muscleGroup: 'Shoulders', equipmentType: 'dumbbell' },
  { name: 'Dumbbell upright row', muscleGroup: 'Shoulders', equipmentType: 'dumbbell' },
  { name: 'Dumbbell curl', muscleGroup: 'Biceps', equipmentType: 'dumbbell' },
  { name: 'Incline dumbbell curl', muscleGroup: 'Biceps', equipmentType: 'dumbbell' },
  { name: 'Dumbbell preacher curl', muscleGroup: 'Biceps', equipmentType: 'dumbbell' },
  { name: 'Spider curl', muscleGroup: 'Biceps', equipmentType: 'dumbbell' },
  { name: 'Hammer curl', muscleGroup: 'Biceps', equipmentType: 'dumbbell' },
  { name: 'Cross-body hammer curl', muscleGroup: 'Biceps', equipmentType: 'dumbbell' },
  { name: 'Concentration curl', muscleGroup: 'Biceps', equipmentType: 'dumbbell' },
  { name: 'Zottman curl', muscleGroup: 'Biceps', equipmentType: 'dumbbell' },
  { name: 'Dumbbell reverse curl', muscleGroup: 'Biceps', equipmentType: 'dumbbell' },
  { name: 'Tricep kickback', muscleGroup: 'Triceps', equipmentType: 'dumbbell' },
  { name: 'Dumbbell overhead extension', muscleGroup: 'Triceps', equipmentType: 'dumbbell' },
  { name: 'Dumbbell skull crusher', muscleGroup: 'Triceps', equipmentType: 'dumbbell' },
  { name: 'Close-grip dumbbell press', muscleGroup: 'Triceps', equipmentType: 'dumbbell' },
  { name: 'Dumbbell shrug', muscleGroup: 'Traps', equipmentType: 'dumbbell' },
  { name: 'Goblet squat', muscleGroup: 'Quads', equipmentType: 'dumbbell' },
  { name: 'Dumbbell front squat', muscleGroup: 'Quads', equipmentType: 'dumbbell' },
  { name: 'Dumbbell lunge', muscleGroup: 'Quads', equipmentType: 'dumbbell' },
  { name: 'Dumbbell reverse lunge', muscleGroup: 'Quads', equipmentType: 'dumbbell' },
  { name: 'Dumbbell walking lunge', muscleGroup: 'Quads', equipmentType: 'dumbbell' },
  { name: 'Dumbbell lateral lunge', muscleGroup: 'Quads', equipmentType: 'dumbbell' },
  { name: 'Dumbbell Bulgarian split squat', muscleGroup: 'Quads', equipmentType: 'dumbbell' },
  { name: 'Dumbbell step-up', muscleGroup: 'Quads', equipmentType: 'dumbbell' },
  { name: 'Dumbbell Romanian deadlift', muscleGroup: 'Hamstrings', equipmentType: 'dumbbell' },
  { name: 'Dumbbell deadlift', muscleGroup: 'Hamstrings', equipmentType: 'dumbbell' },
  { name: 'Dumbbell hip thrust', muscleGroup: 'Glutes', equipmentType: 'dumbbell' },
  { name: 'Kettlebell swing', muscleGroup: 'Glutes', equipmentType: 'dumbbell' },
  { name: 'Dumbbell calf raise', muscleGroup: 'Calves', equipmentType: 'dumbbell' },
  { name: 'Dumbbell side bend', muscleGroup: 'Abs', equipmentType: 'dumbbell' },
  { name: 'Dumbbell wrist curl', muscleGroup: 'Forearms', equipmentType: 'dumbbell' },
  { name: 'Dumbbell reverse wrist curl', muscleGroup: 'Forearms', equipmentType: 'dumbbell' },
  { name: "Farmer's carry", muscleGroup: 'Forearms', equipmentType: 'dumbbell' },
  { name: 'Suitcase carry', muscleGroup: 'Forearms', equipmentType: 'dumbbell' },

  // Machine
  { name: 'Chest press', muscleGroup: 'Chest', equipmentType: 'machine' },
  { name: 'Incline chest press', muscleGroup: 'Chest', equipmentType: 'machine' },
  { name: 'Decline chest press', muscleGroup: 'Chest', equipmentType: 'machine' },
  { name: 'Pec deck', muscleGroup: 'Chest', equipmentType: 'machine' },
  { name: 'Smith machine bench press', muscleGroup: 'Chest', equipmentType: 'machine' },
  { name: 'Smith machine incline press', muscleGroup: 'Chest', equipmentType: 'machine' },
  { name: 'Seated row', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'High row', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'Low row', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'Chest-supported row', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'Iso-lateral row', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'Smith machine row', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'Lat pulldown machine', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'Pullover machine', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'Back extension machine', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'Assisted pull-up', muscleGroup: 'Back', equipmentType: 'machine' },
  { name: 'Shoulder press', muscleGroup: 'Shoulders', equipmentType: 'machine' },
  { name: 'Smith machine shoulder press', muscleGroup: 'Shoulders', equipmentType: 'machine' },
  { name: 'Lateral raise machine', muscleGroup: 'Shoulders', equipmentType: 'machine' },
  { name: 'Reverse pec deck', muscleGroup: 'Shoulders', equipmentType: 'machine' },
  { name: 'Bicep curl machine', muscleGroup: 'Biceps', equipmentType: 'machine' },
  { name: 'Preacher curl machine', muscleGroup: 'Biceps', equipmentType: 'machine' },
  { name: 'Assisted dip', muscleGroup: 'Triceps', equipmentType: 'machine' },
  { name: 'Dip machine', muscleGroup: 'Triceps', equipmentType: 'machine' },
  { name: 'Tricep extension machine', muscleGroup: 'Triceps', equipmentType: 'machine' },
  { name: 'Machine shrug', muscleGroup: 'Traps', equipmentType: 'machine' },
  { name: 'Leg press', muscleGroup: 'Quads', equipmentType: 'machine' },
  { name: 'Hack squat', muscleGroup: 'Quads', equipmentType: 'machine' },
  { name: 'Pendulum squat', muscleGroup: 'Quads', equipmentType: 'machine' },
  { name: 'Belt squat', muscleGroup: 'Quads', equipmentType: 'machine' },
  { name: 'Smith machine squat', muscleGroup: 'Quads', equipmentType: 'machine' },
  { name: 'Leg extension', muscleGroup: 'Quads', equipmentType: 'machine' },
  { name: 'Seated leg curl', muscleGroup: 'Hamstrings', equipmentType: 'machine' },
  { name: 'Lying leg curl', muscleGroup: 'Hamstrings', equipmentType: 'machine' },
  { name: 'Standing leg curl', muscleGroup: 'Hamstrings', equipmentType: 'machine' },
  { name: 'Glute ham raise', muscleGroup: 'Hamstrings', equipmentType: 'machine' },
  { name: 'Hip thrust machine', muscleGroup: 'Glutes', equipmentType: 'machine' },
  { name: 'Hip abductor', muscleGroup: 'Glutes', equipmentType: 'machine' },
  { name: 'Hip adductor', muscleGroup: 'Glutes', equipmentType: 'machine' },
  { name: 'Glute kickback machine', muscleGroup: 'Glutes', equipmentType: 'machine' },
  { name: 'Standing calf raise', muscleGroup: 'Calves', equipmentType: 'machine' },
  { name: 'Seated calf raise', muscleGroup: 'Calves', equipmentType: 'machine' },
  { name: 'Calf press', muscleGroup: 'Calves', equipmentType: 'machine' },
  { name: 'Donkey calf raise', muscleGroup: 'Calves', equipmentType: 'machine' },
  { name: 'Smith machine calf raise', muscleGroup: 'Calves', equipmentType: 'machine' },
  { name: 'Ab crunch machine', muscleGroup: 'Abs', equipmentType: 'machine' },
  { name: 'Torso rotation machine', muscleGroup: 'Abs', equipmentType: 'machine' },
  { name: 'Leg raise machine', muscleGroup: 'Abs', equipmentType: 'machine' },

  // Cable
  { name: 'Cable fly', muscleGroup: 'Chest', equipmentType: 'cable' },
  { name: 'High-to-low cable fly', muscleGroup: 'Chest', equipmentType: 'cable' },
  { name: 'Low-to-high cable fly', muscleGroup: 'Chest', equipmentType: 'cable' },
  { name: 'Cable chest press', muscleGroup: 'Chest', equipmentType: 'cable' },
  { name: 'Cable crossover', muscleGroup: 'Chest', equipmentType: 'cable' },
  { name: 'Single-arm cable fly', muscleGroup: 'Chest', equipmentType: 'cable' },
  { name: 'Incline cable fly', muscleGroup: 'Chest', equipmentType: 'cable' },
  { name: 'Cable incline press', muscleGroup: 'Chest', equipmentType: 'cable' },
  { name: 'Cable row', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Single-arm cable row', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Lat pulldown', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Wide-grip lat pulldown', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Close-grip lat pulldown', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Reverse-grip lat pulldown', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Neutral-grip lat pulldown', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Straight-arm pulldown', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Cable pullover', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Wide-grip cable row', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Close-grip cable row', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Neutral-grip cable row', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Rope cable row', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Cable high row', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Single-arm lat pulldown', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Kneeling lat pulldown', muscleGroup: 'Back', equipmentType: 'cable' },
  { name: 'Face pull', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Cable lateral raise', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Cable front raise', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Cable rear delt fly', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Cable rear delt row', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Cable upright row', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Cable Y-raise', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Single-arm cable lateral raise', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Behind-the-back cable lateral raise', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Cable external rotation', muscleGroup: 'Shoulders', equipmentType: 'cable' },
  { name: 'Cable curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Single-arm cable curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Cable preacher curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Cable overhead curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Rope hammer curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Cable reverse curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Bayesian cable curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Cable drag curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'High cable curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Cable spider curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Cable concentration curl', muscleGroup: 'Biceps', equipmentType: 'cable' },
  { name: 'Tricep pushdown', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Rope tricep pushdown', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Single-arm tricep pushdown', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Reverse-grip tricep pushdown', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Overhead cable tricep extension', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Cable skull crusher', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Cable tricep kickback', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Straight-bar tricep pushdown', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'V-bar tricep pushdown', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Cross-body cable extension', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Single-arm overhead cable extension', muscleGroup: 'Triceps', equipmentType: 'cable' },
  { name: 'Cable shrug', muscleGroup: 'Traps', equipmentType: 'cable' },
  { name: 'Cable high pull', muscleGroup: 'Traps', equipmentType: 'cable' },
  { name: 'Cable Romanian deadlift', muscleGroup: 'Hamstrings', equipmentType: 'cable' },
  { name: 'Cable kickback', muscleGroup: 'Glutes', equipmentType: 'cable' },
  { name: 'Cable pull-through', muscleGroup: 'Glutes', equipmentType: 'cable' },
  { name: 'Cable hip abduction', muscleGroup: 'Glutes', equipmentType: 'cable' },
  { name: 'Cable hip adduction', muscleGroup: 'Glutes', equipmentType: 'cable' },
  { name: 'Cable crunch', muscleGroup: 'Abs', equipmentType: 'cable' },
  { name: 'Cable woodchopper', muscleGroup: 'Abs', equipmentType: 'cable' },
  { name: 'Cable side bend', muscleGroup: 'Abs', equipmentType: 'cable' },
  { name: 'Pallof press', muscleGroup: 'Abs', equipmentType: 'cable' },
  { name: 'Cable oblique crunch', muscleGroup: 'Abs', equipmentType: 'cable' },
  { name: 'Cable reverse crunch', muscleGroup: 'Abs', equipmentType: 'cable' },
  { name: 'Behind-the-back cable wrist curl', muscleGroup: 'Forearms', equipmentType: 'cable' },
  { name: 'Cable wrist curl', muscleGroup: 'Forearms', equipmentType: 'cable' },
  { name: 'Cable reverse wrist curl', muscleGroup: 'Forearms', equipmentType: 'cable' },

  // Bodyweight
  { name: 'Push-up', muscleGroup: 'Chest', equipmentType: 'bodyweight' },
  { name: 'Wide push-up', muscleGroup: 'Chest', equipmentType: 'bodyweight' },
  { name: 'Incline push-up', muscleGroup: 'Chest', equipmentType: 'bodyweight' },
  { name: 'Decline push-up', muscleGroup: 'Chest', equipmentType: 'bodyweight' },
  { name: 'Pull-up', muscleGroup: 'Back', equipmentType: 'bodyweight' },
  { name: 'Wide-grip pull-up', muscleGroup: 'Back', equipmentType: 'bodyweight' },
  { name: 'Neutral-grip pull-up', muscleGroup: 'Back', equipmentType: 'bodyweight' },
  { name: 'Chin-up', muscleGroup: 'Back', equipmentType: 'bodyweight' },
  { name: 'Inverted row', muscleGroup: 'Back', equipmentType: 'bodyweight' },
  { name: 'Pike push-up', muscleGroup: 'Shoulders', equipmentType: 'bodyweight' },
  { name: 'Handstand push-up', muscleGroup: 'Shoulders', equipmentType: 'bodyweight' },
  { name: 'Dip', muscleGroup: 'Triceps', equipmentType: 'bodyweight' },
  { name: 'Bench dip', muscleGroup: 'Triceps', equipmentType: 'bodyweight' },
  { name: 'Diamond push-up', muscleGroup: 'Triceps', equipmentType: 'bodyweight' },
  { name: 'Bodyweight squat', muscleGroup: 'Quads', equipmentType: 'bodyweight' },
  { name: 'Bodyweight lunge', muscleGroup: 'Quads', equipmentType: 'bodyweight' },
  { name: 'Bulgarian split squat', muscleGroup: 'Quads', equipmentType: 'bodyweight' },
  { name: 'Pistol squat', muscleGroup: 'Quads', equipmentType: 'bodyweight' },
  { name: 'Jump squat', muscleGroup: 'Quads', equipmentType: 'bodyweight' },
  { name: 'Box jump', muscleGroup: 'Quads', equipmentType: 'bodyweight' },
  { name: 'Step-up', muscleGroup: 'Quads', equipmentType: 'bodyweight' },
  { name: 'Sissy squat', muscleGroup: 'Quads', equipmentType: 'bodyweight' },
  { name: 'Nordic curl', muscleGroup: 'Hamstrings', equipmentType: 'bodyweight' },
  { name: 'Hyperextension', muscleGroup: 'Hamstrings', equipmentType: 'bodyweight' },
  { name: 'Glute bridge', muscleGroup: 'Glutes', equipmentType: 'bodyweight' },
  { name: 'Single-leg glute bridge', muscleGroup: 'Glutes', equipmentType: 'bodyweight' },
  { name: 'Reverse hyperextension', muscleGroup: 'Glutes', equipmentType: 'bodyweight' },
  { name: 'Calf raise', muscleGroup: 'Calves', equipmentType: 'bodyweight' },
  { name: 'Single-leg calf raise', muscleGroup: 'Calves', equipmentType: 'bodyweight' },
  { name: 'Plank', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Side plank', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Hollow hold', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Dead bug', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Crunch', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Reverse crunch', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Bicycle crunch', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Sit-up', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'V-up', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Hanging leg raise', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Toes-to-bar', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Russian twist', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Ab wheel rollout', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
  { name: 'Mountain climber', muscleGroup: 'Abs', equipmentType: 'bodyweight' },
];
